apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: cluster-infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics
    targetRevision: 5.37.0
    helm:
      valuesObject:
        prometheus:
          monitor:
            enabled: "true"
            honorLabels: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-observability-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
