apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: operator-prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec: 
  channel: beta
  name: prometheus
  source: operatorhubio-catalog
  sourceNamespace: operator-lifecycle-manager