apiVersion: apps/v1
kind: Deployment
metadata:
  name: butterfly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: butterfly
  template:
    metadata:
      labels:
        app: butterfly
        logging: enabled
    spec:
      containers:
        - name: butterfly
          image: ghcr.io/konstfish/aquarium_butterfly:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_URI
              value: "redis://redis:6379/0"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector-headless:4318"
          ports:
            - containerPort: 4004
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4004
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3