apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: onprem-proxy
  labels:
    app: sonarr
spec:
 ports:
  - protocol: TCP
    name: http
    port: 8989
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: sonarr-1
  namespace: onprem-proxy
  labels:
    kubernetes.io/service-name: sonarr
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8989
endpoints:
  - addresses:
      - "10.0.1.1"
