apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: onprem-proxy
  labels:
    app: radarr
spec:
 ports:
  - protocol: TCP
    name: http
    port: 7878
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: radarr-1
  namespace: onprem-proxy
  labels:
    kubernetes.io/service-name: radarr
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 7878
endpoints:
  - addresses:
      - "10.0.1.1"