---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore-secret
  namespace: cluster-observability-monitoring
spec:
  encryptedData:
    thanos.yaml: AgCWTJH0QKb2+qJoKOGHtj7j/zkJc9pKYQCGd0UvbPlTY/dzM/3hCbWyKFfA2QLLSdcBsOCAxgXIK0Wfi4bC+p+KgEpA2DrkcjvFpQoKGl6yLFAPuQENyPcaSADXanfSmcXBJIRHd0gy6Aix/7cjSUMaNBLblXBJoJrusafgkBgUVvs06FOJiJ/exk8/Sj5RlB11hmh4xdaFjuiJdIBpfv8p8+rOXiyEyPv0UQUJpLlC8T2TSYNwd0j8Jnyml7ozF9p3CiG1RpW3AJ8NnI08rGxCIB8ABr7TXWzBVuMx30akjmP2fAS73LEnHpvZJ6VGrQdto8GrDQoNfyIZiJgKEI+CCexgZhiDO7dz2a4sbEXdPUOSS/w/cREnHQqCfhJI9zhMdJYOrWCof/gXiQZmQfTWtvSxGJln9JpSwBXYTkF7jRkv34z04iyKyqkR0gGYaZvfPQX00HxVakMioqXUM+FbIsByBTCZxZs2DU8rqNMKz3y3Q3Vh0IBiR+1+/KgnNNXPpgylTDdlo0xX1q30ZPoxoGjHm0XzCkZTDINHPACvVGxW2jQrEzJvo+3x6xKuqjY4oubz94GTi42GeH/ILOXQFpKXJE94Xn8jXbqaEZN6YzfG+9P+OSCNhPg6b4Pi9ZIdOXyW/e6OZzLiE1pvWbpyJkCAxdtRFJ375G4Q2RpEqLJ2A3fP6aJI/sWb4jjaGrP1Ek4YYormBLJ7bS1t06AYaNLNvRGS+oFfCcfPSMXihV84UXK5kKpXZ/CNovVE5yUFG28phOmaCGMO2xm0Qw327RmpNdZSwgHmCdTbxpNQ+RQFdBstJajbBET1Yj4M0h/UhC0eNBjFQ3/AjVsFRnxoSVwPgoWeLLEcKMV84jGOA4ZcCqF8yyxvZrt8uPVSZqBrmCbtRs2yK+4+Zi9ff66qoAktRdoSnmcwlqLrTzT0
  template:
    metadata:
      name: thanos-objstore-secret
      namespace: cluster-observability-monitoring
    type: Opaque
