---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore-secret
  namespace: cluster-infra-argocd
spec:
  encryptedData:
    thanos.yaml: AgAFYlrCiwLy84FyTNJyD+AkNiBUcdtWEeGe4KHwSW6DCeklE2KA7ib78rFxmRg5vYvnwg5BmNKkfYt3CT4IHesxl17kcZAQ1YHAe7hmGyotNFRVoS3ZnUbX86EYP6ms9Qb7mMthA4+lgg5vWz6WvNzQyI0qkYMQqtN3/df8HJbqxYBnlU8kt+15nVc42/zrwtcmQ7oZqJgwt2ixeb6SKlFhklTxmkAibbBMFr6HNburzf9nLcKfLaqTQkJ4biFAriOXPlnINMpaBmHl1IQsJVsa8oZLAwmotVRk/GUmM0Db2dAeB7F+Y5HAz9XNXf4DHAUnLv/wHNd/LGeqWR+Qo296aaadwDKp+i1PsvN6PRS8Q7IwV9246pDowarkyVkbA8/fbx5e1lB2V2E2zMNj7tqq8tIWwKh8+IVEtcv0gHXtDR6LIpHc7tG3IpySScqDydcxAKpP7gOrX1gCLI+yFnXLXwyluSRTpqEK2d6tfpE1pIq3uLWJUskMts9TfOPpXh3o8oc2WfE3Sdd5sZq2bhNuGT0GwqcOj88BGLF5YJpsjy++nEEJoPTZhK5EoRsE1/13hPMimhsvMvgI9+tGhjx5Qs7oQmpSM1KqGq9c/FmRHk7SC45vXS1dTA7IemrV3ITRyrl4fYv29P8+aijNeF09BvKxNnz6171Lxyb60IfVhJScVSbXUQ9sKOmQr3Dl74I4jYIatMsLcodNx6Wi3lbDlymXbuS2AjrAuq/+5j0Up0s+V1fscHtYjhVilSPmfMnTVwjwAiVnuQOYCSNgk0EdZsXXOrgsJPlElKmCTfyaXvyx/wiqXo347tYJl0ygamr8bwwJW9cjiKvOfcvwVteLc8HFlyzGPNXuFRh+0oaI3LvuFb/K/5ZCeWkTGlHaf/Aop1BRjMvAa5CrsUiLz2yPoacCNCzlYzKgrKQ3zT0/
  template:
    metadata:
      name: thanos-objstore-secret
      namespace: cluster-infra-argocd
    type: Opaque
