apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: onprem-proxy
  labels:
    app: prowlarr
spec:
 ports:
  - protocol: TCP
    name: http
    port: 9696
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: prowlarr-1
  namespace: onprem-proxy
  labels:
    kubernetes.io/service-name: prowlarr
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 9696
endpoints:
  - addresses:
      - "10.0.1.1"