apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: knative-serving
data:
  external-gateways: |
    - class: istio
      gateway: istio-ingress/http-gateway
      service: istio-ingress/http-gateway-istio
      supported-features:
        - HTTPRouteRequestTimeout
  local-gateways: |
    - class: istio
      gateway: istio-ingress/http-gateway
      service: istio-ingress/http-gateway-istio
      supported-features:
        - HTTPRouteRequestTimeout
