namespace: knative-serving

resources:
  - ns.yaml
  - cert.yaml
  - serving.yaml
  - peer.yaml
  # service/pod monitors (https://github.com/knative-extensions/monitoring)
  - https://raw.githubusercontent.com/knative-extensions/monitoring/refs/heads/main/config/serving-monitors.yaml
  - https://raw.githubusercontent.com/knative-extensions/monitoring/refs/heads/main/config/eventing-monitors.yaml