apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ingress-netset-secret
spec:
  refreshInterval: 96h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: ingress-netset-secret
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: whitelist_basic_auth