apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fgtconfig
  namespace: knative-app
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: ghcr.io/konstfish/fgtconfig:latest
    spec:
      containerConcurrency: 0
      containers:
      - image: ghcr.io/konstfish/fgtconfig:latest
        name: user-container
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100