apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-ingress

resources:
  - wildcard-internal-tls.yaml
  - wildcard-external-tls.yaml
  - http-gatway.yaml
  - authorizationpolicy.yaml