apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: onprem-proxy
  labels:
    app: transmission
spec:
 ports:
  - protocol: TCP
    name: http
    port: 9091
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: transmission-1
  namespace: onprem-proxy
  labels:
    kubernetes.io/service-name: transmission
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 9091
endpoints:
  - addresses:
      - "10.0.1.1"
