apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-ingress

resources:
  - ../../base
  - http-gateway-netbird.yaml
  #- authorizationpolicy.yaml

patches:
  - patch: http-gateway.yaml
  - path: wildcard-internal-tls.yaml