apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rook-ns.yaml
  - rook-helm.yaml
  - rook-cluster.yaml
  - rook-dashboard-ingress.yaml
  - storage/block-replicated.yaml
  - storage/file-replicated.yaml